### ISSUE TITLE
Rails 5.1 or maybe other issue

### ISSUE THREAD

**Issue by scarroll32** [jedld/pretentious#2]
Looks like a great gem, but I'm having trouble getting started. My setup is:

- added to dev/test group
- bundle
- add initializer

config/initializers/pretentious.rb

```ruby
Pretentious.install_watcher # install watcher if not defined previously
```

config/application.rb

```ruby
if Rails.env.test? || Rails.env.development?
  puts "watching new instances"
  Pretentious::Generator.watch_new_instances
end
```

Start rails console:

```
rails s -e test
```

...Nothing happens when the server is launched

Then try to browse the side -> error

```
An unhandled lowlevel error occurred. The application logs may have details.
```
```
[25386] - Worker 0 (pid: 25402) booted, phase: 0
2017-09-26 14:09:17 +0200: Rack app error handling request { GET / }
#<ActionView::Template::Error: can't modify frozen ActionView::Template::Handlers::ERB::Erubi>
/Users/sean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/pretentious-0.2.3/lib/pretentious/generator.rb:447:in `_set_init_arguments'
/Users/sean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/pretentious-0.2.3/lib/pretentious/generator.rb:520:in `new'
```

Any help would be really appreciated.

**Comment by jedld** [comment]
Should now be fixed on 0.2.4. pretentious still has issues with frozen objects, this will prevent crashes though.
